services:

  backend:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - .app/:/app

  frontend:
    build: frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_INTERVAL=200